highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
port: 4000
safe: true
url: http://burhaninho.github.io/vitae
author: 

# edit this section with your information
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Mohamed Burhan's Resume
name: Mohamed Burhan
email: me@burhaninho.com
email_full: mailto:me@burhaninho.com
website: burhaninho.com
github: burhaninho
twitter: burhaninho
tel: +1 612 618 8159
tel_full: tel:+16126188159
google_maps: 'https://'
address: 1920 Portland Ave S
postcode: 55404-5512
city: Minneapolis, MN
country: USA
google_analytics: UA-69391421-1

